INSERT INTO products_images (url, products_detail_id)
Values 
('imgProducts/duongtoc-dove.jpg' , 1),
('imgProducts/duongtoc-loreal.jpg' , 2),
('imgProducts/duongtoc-ellips.jpg' , 3),
('imgProducts/duongtoc-organist.jpg' , 4),
('imgProducts/daugoi-cocoon.jpg' , 5),
('imgProducts/daugoi-selsun.jpg' , 6),
('imgProducts/daugoi-tresemme.jpg' , 7),
('imgProducts/daugoi-tsubaki-cool.jpg' , 8),
('imgProducts/matna-bnbg-combo10.jpg' , 9),
('imgProducts/matna-caryophy.jpg' , 10),
('imgProducts/matna-klaris.jpg' , 11),
('imgProducts/matna-naruko.jpg' , 12),
('imgProducts/serum-beauty-labo.jpg' , 13),
('imgProducts/serum-cocoon.jpg' , 14),
('imgProducts/serum-tresemme.jpg' , 15),
('imgProducts/serum-ellips.jpg' , 16),
('imgProducts/xittoc-double-rich.jpg' , 17),
('imgProducts/xittoc-hairburst.jpg' , 18),
('imgProducts/xittoc-tresmme.jpg' , 19),
('imgProducts/xittoc-tsubaki.jpg' , 20),
('imgProducts/dauduong-doublerich.png' , 21),
('imgProducts/dauduong-l-oreal.jpg' , 22),
('imgProducts/dauduong-some-by-mi.jpg' , 23),
('imgProducts/dauduong-tsubaki.jpg' , 24);